version: '3'
services:
  hitch-onekey-mysql:
    image: mysql:5.7.43
    container_name: hitch-onekey-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    command:
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./docker-compose-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "9209:3306"
    networks:
      - hitch-onekey-net

  hitch-onekey-rabbitmq:
    image: rabbitmq:3.6.10-management
    container_name: hitch-onekey-rabbitmq
    restart: always
    ports:
      - "9202:15672"
      - "9203:5672"
    networks:
      - hitch-onekey-net

  hitch-onekey-redis:
    image: redis:6.0.6
    container_name: hitch-onekey-redis
    restart: always
    ports:
      - "9204:6379"
    networks:
      - hitch-onekey-net

  hitch-onekey-minio:
    image: minio/minio:RELEASE.2023-12-02T10-51-33Z
    container_name: hitch-onekey-minio
    restart: always
    command: server /data --console-address ":9090" --address ":9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./minio-data:/data
      - ./minio-config:/root/.minio
    ports:
      - "9205:9000"
      - "9206:9090"
    networks:
      - hitch-onekey-net

  hitch-onekey-mongo4:
    image: docker.io/mongo:4.4
    container_name: hitch-onekey-mongo4
    restart: always
    ports:
      - "9207:27017"
    networks:
      - hitch-onekey-net

  hitch-onekey-backend:
    image: hitch-allinone:1.0-SNAPSHOT
    container_name: hitch-onekey-backend
    restart: always
    ports:
      - "9208:8080"
    links:
      - hitch-onekey-mysql
      - hitch-onekey-minio
    depends_on:
      - hitch-onekey-mysql
      - hitch-onekey-minio
    environment:
      server.port: 8080
      spring.datasource.url: jdbc:mysql://hitch-onekey-mysql/hitch?useUnicode=true&characterEncoding=utf-8
      spring.datasource.username: root
      spring.datasource.password: root
      minio.url: http://192.168.64.100:9205
      minio.host: hitch-onekey-minio
      minio.port: 9000
      minio.bucket: hitch
      minio.username: minioadmin
      minio.password: minioadmin
      spring.rabbitmq.host: hitch-onekey-rabbitmq
      spring.rabbitmq.port: 5672
      spring.redis.host: hitch-onekey-redis
      spring.redis.port: 6379
      spring.data.mongodb.host: hitch-onekey-mongo4
      baidu.apikey: 3mWHEPREHzAxeCRq3z6xb8bR
      baidu.secretkey: 33fUD7ztZm1v5uBIwiKZFICPIbcXhgju
      baidu.map.ak: MkIZ2ME6zhPNU1o3BnIzq38Vo38WPz8X
      baidu.map.api: https://api.map.baidu.com/routematrix/v2/driving
    networks:
      - hitch-onekey-net

  hitch-onekey-nginx:
    image: nginx:1.16.1
    container_name: hitch-onekey-nginx
    restart: always
    ports:
      - "9201:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../web:/usr/share/nginx/html/web
    depends_on:
      - hitch-onekey-backend
    networks:
      - hitch-onekey-net

  hitch-onekey-portainer:
    image: portainer/portainer:latest
    container_name: hitch-onekey-portainer
    restart: always
    ports:
      - "9243:9443"
      - "9200:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      - hitch-onekey-net

networks:
  hitch-onekey-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24  


