server:
  port: 8888

spring:
  redis:
    host: 192.168.64.100
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1000
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  data:
    mongodb:
      host: 192.168.64.100
      port: 27017
      database: notice
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.64.100:3306/hitch?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    initialSize: 10
    minIdle: 20
    maxActive: 100
    maxWait: 60000
  rabbitmq:
    host: 192.168.64.100
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#minio的完整url会写入后台的数据库
#例如：http://192.168.64.100:9005/prize/1701754725603.jpeg
#所以要保障其可访问性，尤其是docker部署的时候，应该是宿主机暴露的端口！
minio:
  url: http://192.168.64.100:9005
  host: 192.168.64.100
  port: 9005
  bucket: hitch
  username: minioadmin
  password: minioadmin

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.heima.modules.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

baidu:
  apikey: 3mWHEPREHzAxeCRq3z6xb8bR
  secretkey: 33fUD7ztZm1v5uBIwiKZFICPIbcXhgju
  map:
    ak: MkIZ2ME6zhPNU1o3BnIzq38Vo38WPz8X
    api: https://api.map.baidu.com/routematrix/v2/driving